### ISSUE TITLE
Single page apps

### ISSUE THREAD

**Issue by peebles** [jasonmayes/wsk-component-design-pattern#1]
Have you seen https://github.com/uzairfarooq/arrive?  Bootstrap-material supports it, which makes using it on SPAs real nice.  When new pages get rendered into the DOM, absolutely nothing needs to be done in javascript.  Seems to me your upgradeElement() could be implemented using only the first element argument, and it could discover what to do based on the css classes already present on the element.  Then something like arrive() could be used to automatically materialize any component added to the DOM by a SPA without any additional code.

**Comment by jasonmayes** [comment]
Indeed, but the browser support is IE11+ only. I wanted to go back further for IE9 at least as I know a lot of companies / individuals need to support for that. Also if you just want to search whole DOM and upgrade any elements that have been added and not already upgraded you can simply use upgradeAllRegisteredInternal() which will attempt to do that for all known components.
